### ISSUE TITLE
test_features.py failed

### ISSUE THREAD

**Issue by KSNikolaus** [dgodinez77/LIA#1]
Hi,
running the test_features.py I get the following failed status:

...F...........................................
======================================================================
FAIL: test_abs_energy (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_features.py", line 37, in test_abs_energy
    value.assertEqual( abs_energy(norm_flux), 27.956794796425804, "Absolute Energy function failed")
AssertionError: 27.956794796425797 != 27.956794796425804 : Absolute Energy function failed

----------------------------------------------------------------------
Ran 47 tests in 0.127s

FAILED (failures=1)

This could be just a rounding error since the values only disagree in the last three decimals?

Cheers,
Kay

**Comment by ebachelet** [comment]
It seems so other users have this issue. We gonna explore this.

**Comment by dgodinez77** [comment]
This discrepancy occurs between tesfresh version 0.11.0 and 0.11.3, updated requirements page to specify version 0.11.0
