### ISSUE TITLE
Problem with setup procedures

### ISSUE THREAD

**Issue by KSNikolaus** [dgodinez77/LIA#2]
I have set up a completely new virtual environment to install LIA and cloned the LIA repository. In this virt.env., I have installed all dependencies as described in the requirements.txt. Finally I used python setup.py to install LIA.  When I now import LIA modules as

from LIA import training_set

in python, I always get errors saying that there is no module called like that. It seems the setup procedures do not install the whole package.

**Comment by dgodinez77** [comment]
Fixed -- directory architecture has been simplified to avoid import errors.
