### ISSUE TITLE
unexpected keyword in training set

### ISSUE THREAD

**Issue by mpgh** [dgodinez77/LIA#4]
please update the optional keyword, which is n in module quality check and ml_n1 in the training_set module:

TypeError: test_microlensing() got an unexpected keyword argument 'ml_n1'

line 181             quality = quality_check.test_microlensing(time, mag, magerr, baseline, u_0, t_0, t_e, blend_ratio, ml_n1=ml_n1)

**Comment by dgodinez77** [comment]
Done, thank you!
